import { Gantari } from "next/font/google";
import Footer from "./components/Footer";
import HeaderOne from "./components/HeaderOne";

import "./globals.css";

const gantari = Gantari({
  weight: ["300", "400", "500", "600", "700", "800"],
  subsets: ["latin"],
  display: "swap",
  variable: "--font-gantari",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const fontFamily = `${gantari.variable}`;

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={fontFamily}>
      <body>
        <HeaderOne />
        {children}
        <Footer />
      </body>
    </html>
  );
}
